CREATE TABLE IF NOT EXISTS branches (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL UNIQUE,
    password   TEXT NOT NULL,
    store_id   TEXT NOT NULL DEFAULT '',
    last_login TEXT,
    is_blocked INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (to_char(timezone('Asia/Jerusalem', now()), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS barcodes (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode    TEXT NOT NULL UNIQUE,
    sku        TEXT NOT NULL,
    color      TEXT NOT NULL,
    size       TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (to_char(timezone('Asia/Jerusalem', now()), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_barcodes_sku ON barcodes(sku);
CREATE INDEX IF NOT EXISTS idx_barcodes_barcode ON barcodes(barcode);

CREATE TABLE IF NOT EXISTS barcode_color_scale (
    code       TEXT PRIMARY KEY,
    color      TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (to_char(timezone('Asia/Jerusalem', now()), 'YYYY-MM-DD HH24:MI:SS')),
    updated_at TEXT NOT NULL DEFAULT (to_char(timezone('Asia/Jerusalem', now()), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_barcode_color_scale_color ON barcode_color_scale(color);

CREATE TABLE IF NOT EXISTS barcode_size_scale (
    code       TEXT PRIMARY KEY,
    size       TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (to_char(timezone('Asia/Jerusalem', now()), 'YYYY-MM-DD HH24:MI:SS')),
    updated_at TEXT NOT NULL DEFAULT (to_char(timezone('Asia/Jerusalem', now()), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_barcode_size_scale_size ON barcode_size_scale(size);

CREATE TABLE IF NOT EXISTS morning_sessions (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id    INTEGER NOT NULL REFERENCES branches(id),
    session_date TEXT NOT NULL DEFAULT (to_char(timezone('Asia/Jerusalem', now()), 'YYYY-MM-DD')),
    sku          TEXT NOT NULL,
    color        TEXT NOT NULL,
    sizes_all    TEXT NOT NULL DEFAULT '',
    sizes_found  TEXT NOT NULL DEFAULT '',
    approved     INTEGER NOT NULL DEFAULT 0,
    created_at   TEXT NOT NULL DEFAULT (to_char(timezone('Asia/Jerusalem', now()), 'YYYY-MM-DD HH24:MI:SS')),
    UNIQUE(branch_id, session_date, sku, color)
);
CREATE INDEX IF NOT EXISTS idx_msession_branch ON morning_sessions(branch_id, session_date);
CREATE INDEX IF NOT EXISTS idx_msession_open_lookup ON morning_sessions(branch_id, sku, color) WHERE approved = 0;

CREATE TABLE IF NOT EXISTS missing_floor (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id           INTEGER NOT NULL REFERENCES branches(id),
    sku                 TEXT NOT NULL,
    color               TEXT NOT NULL,
    size                TEXT NOT NULL,
    status              TEXT NOT NULL DEFAULT 'missing',
    source              TEXT NOT NULL DEFAULT 'session',
    manual_session_date TEXT,
    created_at          TEXT NOT NULL DEFAULT (to_char(timezone('Asia/Jerusalem', now()), 'YYYY-MM-DD HH24:MI:SS')),
    resolved_at         TEXT
);
CREATE INDEX IF NOT EXISTS idx_missing_floor_branch ON missing_floor(branch_id, status);
CREATE INDEX IF NOT EXISTS idx_missing_floor_item ON missing_floor(branch_id, sku, color, size) WHERE status = 'missing';

CREATE TABLE IF NOT EXISTS missing_warehouse (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id    INTEGER NOT NULL REFERENCES branches(id),
    sku          TEXT NOT NULL,
    color        TEXT NOT NULL,
    size         TEXT NOT NULL,
    quantity     INTEGER NOT NULL DEFAULT 1,
    scan_history TEXT NOT NULL DEFAULT '',
    status       TEXT NOT NULL DEFAULT 'pending',
    scanned_at   TEXT NOT NULL DEFAULT (to_char(timezone('Asia/Jerusalem', now()), 'YYYY-MM-DD HH24:MI:SS')),
    restocked_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_missing_wh_branch ON missing_warehouse(branch_id, status);
CREATE INDEX IF NOT EXISTS idx_missing_wh_item ON missing_warehouse(branch_id, sku, color, size) WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS warehouse_locations (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id  INTEGER NOT NULL REFERENCES branches(id),
    sku        TEXT NOT NULL,
    location   TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT (to_char(timezone('Asia/Jerusalem', now()), 'YYYY-MM-DD HH24:MI:SS')),
    UNIQUE(branch_id, sku)
);
CREATE INDEX IF NOT EXISTS idx_locations_branch ON warehouse_locations(branch_id);

CREATE TABLE IF NOT EXISTS admins (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   TEXT NOT NULL UNIQUE,
    password   TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (to_char(timezone('Asia/Jerusalem', now()), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS blocked_devices (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id   INTEGER NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    device_id   TEXT NOT NULL,
    device_name TEXT NOT NULL DEFAULT '',
    blocked_at  TEXT NOT NULL DEFAULT (to_char(timezone('Asia/Jerusalem', now()), 'YYYY-MM-DD HH24:MI:SS')),
    UNIQUE(branch_id, device_id)
);
CREATE INDEX IF NOT EXISTS idx_blocked_devices_branch ON blocked_devices(branch_id);
